### ISSUE TITLE
I get an error when trying to publish

### ISSUE THREAD

**Issue by renelopezgomez** [datopian/obsidian-flowershow#19]
Hello, I'm using flowershow for the first time, and I tried to publish a note but I got this error:

[12:41:31.421] Running build in Washington, D.C., USA (East) – iad1
[12:41:31.532] Cloning github.com/renelopezgomez/obsidian_test (Branch: main, Commit: d41a24d)
[12:41:32.338] Cloning completed: 809.171ms
[12:41:38.614] Restored build cache from previous deployment (GFLdHBKrMgDaVbcFYE5BQVUWonZE)
[12:41:38.791] Running "vercel build"
[12:41:41.172] Vercel CLI 39.2.0
[12:41:41.665] Running "install" command: `npm install`...
[12:41:44.479] npm warn ERESOLVE overriding peer dependency
[12:41:44.479] npm warn While resolving: react-virtual@2.10.4
[12:41:44.480] npm warn Found: react@18.2.0
[12:41:44.480] npm warn node_modules/react
[12:41:44.480] npm warn   react@"^18.2.0" from the root project
[12:41:44.480] npm warn   24 more (@docsearch/react, @floating-ui/react-dom, ...)
[12:41:44.480] npm warn
[12:41:44.480] npm warn Could not resolve dependency:
[12:41:44.480] npm warn peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
[12:41:44.480] npm warn node_modules/kbar/node_modules/react-virtual
[12:41:44.480] npm warn   react-virtual@"^2.8.2" from kbar@0.1.0-beta.40
[12:41:44.480] npm warn   node_modules/kbar
[12:41:44.481] npm warn
[12:41:44.481] npm warn Conflicting peer dependency: react@17.0.2
[12:41:44.481] npm warn node_modules/react
[12:41:44.481] npm warn   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
[12:41:44.481] npm warn   node_modules/kbar/node_modules/react-virtual
[12:41:44.481] npm warn     react-virtual@"^2.8.2" from kbar@0.1.0-beta.40
[12:41:44.481] npm warn     node_modules/kbar
[12:41:50.306] 
[12:41:50.307] up to date, audited 993 packages in 8s
[12:41:50.307] 
[12:41:50.308] 311 packages are looking for funding
[12:41:50.308]   run `npm fund` for details
[12:41:50.366] 
[12:41:50.366] 28 vulnerabilities (3 low, 6 moderate, 19 high)
[12:41:50.366] 
[12:41:50.371] To address issues that do not require attention, run:
[12:41:50.371]   npm audit fix
[12:41:50.371] 
[12:41:50.371] Some issues need review, and may require choosing
[12:41:50.371] a different dependency.
[12:41:50.372] 
[12:41:50.372] Run `npm audit` for details.
[12:41:50.386] Detected Next.js version: 13.3.0
[12:41:50.387] Running "npm run export"
[12:41:50.560] 
[12:41:50.563] > flowershow@2.0.3 export
[12:41:50.563] > npm run build && next export
[12:41:50.563] 
[12:41:50.698] 
[12:41:50.699] > flowershow@2.0.3 prebuild
[12:41:50.699] > npm run generate
[12:41:50.699] 
[12:41:50.834] 
[12:41:50.834] > flowershow@2.0.3 generate
[12:41:50.834] > cross-env NODE_OPTIONS="--experimental-json-modules --experimental-modules" node -r esbuild-register ./scripts/prebuild.mjs
[12:41:50.834] 
[12:41:51.630] 
[12:41:51.631] > flowershow@2.0.3 build
[12:41:51.631] > next build
[12:41:51.631] 
[12:41:51.879] (node:201) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[12:41:51.880] (Use `node --trace-deprecation ...` to show where the warning was created)
[12:41:52.141] info  - Skipping linting
[12:41:52.144] info  - Checking validity of types...
[12:41:54.945] info  - Creating an optimized production build...
[12:42:13.935] Browserslist: caniuse-lite is outdated. Please run:
[12:42:13.936]   npx update-browserslist-db@latest
[12:42:13.936]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[12:42:16.766] info  - Compiled successfully
[12:42:16.790] info  - Collecting page data...
[12:42:20.372] info  - Generating static pages (0/7)
[12:42:20.580] SyntaxError: Arg string terminates parameters early
[12:42:20.580]     at new Function (<anonymous>)
[12:42:20.581]     at file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:64:35
[12:42:20.581]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[12:42:20.581]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[12:42:20.581]     at MDXRemote (file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:52:21)
[12:42:20.581]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[12:42:20.581]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[12:42:20.581]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[12:42:20.581]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[12:42:20.581]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[12:42:20.582] 
[12:42:20.582] Error occurred prerendering page "/flowershow". Read more: https://nextjs.org/docs/messages/prerender-error
[12:42:20.582] SyntaxError: Arg string terminates parameters early
[12:42:20.582]     at new Function (<anonymous>)
[12:42:20.582]     at file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:64:35
[12:42:20.582]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[12:42:20.583]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[12:42:20.583]     at MDXRemote (file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:52:21)
[12:42:20.583]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[12:42:20.583]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[12:42:20.583]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[12:42:20.583]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[12:42:20.583]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[12:42:20.584] info  - Generating static pages (1/7)
[12:42:20.625] info  - Generating static pages (3/7)
[12:42:20.637] info  - Generating static pages (5/7)
[12:42:20.777] SyntaxError: Arg string terminates parameters early
[12:42:20.779]     at new Function (<anonymous>)
[12:42:20.780]     at file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:64:35
[12:42:20.780]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[12:42:20.780]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[12:42:20.780]     at MDXRemote (file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:52:21)
[12:42:20.780]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[12:42:20.780]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[12:42:20.780]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[12:42:20.780]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[12:42:20.780]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[12:42:20.780] 
[12:42:20.780] Error occurred prerendering page "/problema del mal". Read more: https://nextjs.org/docs/messages/prerender-error
[12:42:20.780] SyntaxError: Arg string terminates parameters early
[12:42:20.780]     at new Function (<anonymous>)
[12:42:20.780]     at file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:64:35
[12:42:20.780]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[12:42:20.780]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[12:42:20.780]     at MDXRemote (file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:52:21)
[12:42:20.780]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[12:42:20.780]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[12:42:20.780]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[12:42:20.780]     at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[12:42:20.780]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[12:42:20.780] 
[12:42:20.780] > Export encountered errors on following paths:
[12:42:20.781] 	/[[...slug]]: /flowershow
[12:42:20.781] 	/[[...slug]]: /problema del mal
[12:42:20.781] info  - Generating static pages (7/7)
[12:42:20.820] Error: Command "npm run export" exited with 1
[12:42:21.145]

**Comment by rufuspollock** [comment]
DUPLICATE. This is also asked on the main forum and we've responded there 😄
